### ISSUE TITLE
initial release TODO

### ISSUE THREAD

**Issue by neuecc** [Cysharp/csbindgen#1]
- [x] rewrite rust emitter
- [x] collect extern(out) rust method
- [x] builder API
- [x] method filter
- [x] C# method name entrypoint
- [x] configurable emitter
- [ ] GitHub Action
- [x] ReadMe
- [x] Add vendor.yml (ignore c dir)
- [x] More generate check
  - [x] ZStandard
  - [x] quiche
  - [x] bullet physics
- [x] Upload to crates.io
